import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { Vazirmatn } from "next/font/google";
import "./globals.css";

import ToasterContext from "./context/ToasterContext";
import AuthContext from "./context/AuthContext";

// const inter = Inter({ subsets: ["latin"] });
const vazirmatn = Vazirmatn({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Messenger",
  description: "Generated by ParsaNaderi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={vazirmatn.className}>
        <AuthContext>
          <ToasterContext />
          {children}
        </AuthContext>
      </body>
    </html>
  );
};